# Generated by Django 5.1.3 on 2025-05-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transactions/')),
                ('extracted_text', models.TextField(blank=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
