# Generated by Django 5.2.8 on 2026-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_day_wise_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_day_wise',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('monthexpences', 'month expences'), ('food', 'Food'), ('helth', 'helth gedget'), ('helthfood', 'helth food'), ('transport', 'Transport'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=50),
        ),
    ]
